version: 2
jobs:
  build:
    docker:
      - image: docker

    steps:
      - checkout

      - setup_remote_docker:
          docker_layer_caching: true

      - run: |
          docker build -t bitionaire/node-web-app .
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          docker push bitionaire/node-web-app:latest